[package]
name = "torpid"
version = "0.1.3"
authors = ["nk"]
edition = "2018"
license = "MIT"
description = "Tiny linux utility to turn CPU cores on/off"
repository = "https://github.com/n-k/torpid"

[dependencies]
clap = "2.33.3"
